### PR TITLE
Feature: Player current, volume, mute and queue/meta endpoints

### LINKED ISSUE #3: Add player/current end point

### PR DESCRIPTION
**Pull request by edoparearyee**
This PR adds the following end points:
- `/api/player/current`
- `/api/player/volume`
- `/api/player/mute`
- `/api/player/queue/meta`

Fixes #3 #4 #5

### CODE REVIEW

**Comment by jamesjwarren** [comment]
@edwardoparearyee using the `findone` name for this new blueprint will conflict with the default `findone` blueprint which I can imagine we may want to use for `/tracks/:id` `/users/:id` in the future.

**Comment by edoparearyee** [comment]
@jamesjwarren your right, good spot

**Comment by edoparearyee** [comment]
@jamesjwarren should be fixed now

**Comment by jamesjwarren** [comment]
LGTM :+1:

**Pull request merged**
