### PR TITLE
Feature: blueprints

### PR DESCRIPTION
**Pull request by jamesjwarren**
This PR moves FM API queries into blueprints for reusability.

### CODE REVIEW

**Comment by jamesjwarren** [comment]
@edwardoparearyee this is ready for another review. I've added the option for setting the service to use in the route config. This could enable us to configure additional micro services by adding a new service `services/newService.js` and adding routes with `service='newservice'`. This makes the blueprints generic so they can be re-used as much as possible.

**Comment by edoparearyee** [comment]
@jamesjwarren doesn't seem to load data from the api for me. In fact the request is not hitting the API at all.

**Comment by jamesjwarren** [comment]
@edwardoparearyee did you run it with `sails lift --prod`? At the moment it should hit the local sails models in `development` mode and FM API at localdocker in `production` mode. If we need additional environments; like a secondary development environment that hits localdocker, and the production environment hitting the real API we could configure that.

**Comment by edoparearyee** [comment]
No i didn't works now. :smile: 

LGTM :+1:

**Comment by jamesjwarren** [comment]
Sorry, should've said that in the PR.

**Pull request merged**
