### PR TITLE
Feature: Complete queue endpoint

### LINKED ISSUE #1: Add player/queue end point
Complete end point for 'player/queue'

### PR DESCRIPTION
**Pull request by edoparearyee**
This PR nest the `/queue` end point under `/player` to match the API and makes sure that query params are passed to the API as well.

Fixes #1

### CODE REVIEW

**Comment by edoparearyee** [comment]
This should be ready now, but probably best to wait till #9 is merged

**Comment by jamesjwarren** [comment]
Cool, I'll update my PR

**Comment by edoparearyee** [comment]
okay i'll merge this in the mean time then if there are no objections and you can resolve the merge conflicts if you can.

**Comment by jamesjwarren** [comment]
Yeh thats fine :+1:

**Pull request merged**
